### ISSUE TITLE
Is there a way to control the padding/size of the toggle buttons?

### ISSUE THREAD

**Issue by ghunter99** [csells/flutter_toggle_buttons#1]
I apologise if this is not the best place to create an issue.

Here's a screenshot with more than 3 buttons, overflowing the screen:
![Screenshot_1568186692](https://user-images.githubusercontent.com/935432/64676552-2ec1c580-d4b9-11e9-9af6-ab908a14a781.png)

...and here's a screenshot of what I'd like to do from https://material.io/components/buttons/#toggle-button:
<img width="359" alt="screenshot_from_material_design_web_site" src="https://user-images.githubusercontent.com/935432/64676956-fe2e5b80-d4b9-11e9-9e39-fe34a1e99673.png">

- Gary

**Comment by csells** [comment]
Those black & yellow lines are an indication that you've overflowed the space provided by the parent. You can see recommendations about how to fix that in the debug output of you program.

To create the standard Apple-style toolbar, you can create multiple ToggleButtons widgets in a Row, providing a space between them with a Spacer widget.

**Comment by csells** [comment]
Also, check out https://github.com/flutter/flutter/pull/39857 for updates to support your use case specifically.

**Comment by ghunter99** [comment]
Thanks Chris. I should have checked out  [flutter/flutter#39857]( flutter/flutter#39857) first
